# For production (after deploying to Netlify with Identity enabled)
backend:
  name: git-gateway
  branch: main

# For local development testing, uncomment the line below and comment out git-gateway above
# backend:
#   name: test-repo

local_backend: true

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "products"
    label: "Products"
    folder: "src/content/products"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Price", name: "price", widget: "string", required: false }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Order", name: "order", widget: "number", default: 0 }

  - name: "gallery"
    label: "Gallery"
    folder: "src/content/gallery"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Order", name: "order", widget: "number", default: 0 }

  - name: "site"
    label: "Site Settings"
    files:
      - label: "Site Info"
        name: "info"
        file: "src/content/siteinfo.json"
        fields:
          - { label: "Site Title", name: "title", widget: "string" }
          - { label: "Tagline", name: "tagline", widget: "string" }
          - { label: "Hero Text", name: "heroText", widget: "text" }
          - { label: "Instagram Handle", name: "instagram", widget: "string" }
          - { label: "Instagram URL", name: "instagramUrl", widget: "string" }
          - { label: "Email", name: "email", widget: "string" }
          - { label: "About Text", name: "aboutText", widget: "markdown" }
